name: v9-e

anchor:
  reg_max: 16
  strides: [8, 16, 32]

model:
  backbone:
    - Conv:
        args: {out_channels: 64, kernel_size: 3, stride: 2}
        source: 0
        tags: L1
    - Conv:
        args: {out_channels: 128, kernel_size: 3, stride: 2}
    - RepNCSPELAN:
        args:
          out_channels: 256
          part_channels: 128
          process_channels: 64
          csp_args: {repeat_num: 2}
        tags: L3

    - ADown:
        args: {out_channels: 256}
    - RepNCSPELAN:
        args:
          out_channels: 512
          part_channels: 256
          process_channels: 128
          csp_args: {repeat_num: 2}
        tags: B3

    - ADown:
        args: {out_channels: 512}
    - RepNCSPELAN:
        args:
          out_channels: 1024
          part_channels: 512
          process_channels: 256
          csp_args: {repeat_num: 2}
        tags: B4

    - ADown:
        args: {out_channels: 1024}
    - RepNCSPELAN:
        args:
          out_channels: 1024
          part_channels: 512
          process_channels: 256
          csp_args: {repeat_num: 2}
        tags: B5

    # Routing taps as in v9-e (layers 1,3,5,7,9)
    - CBLinear:
        source: L1
        args: {out_channels: [64]}
        tags: RT1
    - CBLinear:
        source: L3
        args: {out_channels: [64, 128]}
        tags: RT3
    - CBLinear:
        source: B3
        args: {out_channels: [64, 128, 256]}
        tags: RT5
    - CBLinear:
        source: B4
        args: {out_channels: [64, 128, 256, 512]}
        tags: RT7
    - CBLinear:
        source: B5
        args: {out_channels: [64, 128, 256, 512, 1024]}
        tags: RT9

    # Fused backbone stages
    - Conv:
        args: {out_channels: 64, kernel_size: 3, stride: 2}
        source: 0
    - CBFuse:
        source: [RT1, RT3, RT5, RT7, RT9, -1]
        args: {index: [0, 0, 0, 0, 0]}

    - Conv:
        args: {out_channels: 128, kernel_size: 3, stride: 2}
    - CBFuse:
        source: [RT3, RT5, RT7, RT9, -1]
        args: {index: [1, 1, 1, 1]}

    - RepNCSPELAN:
        args:
          out_channels: 256
          part_channels: 128
          process_channels: 64
          csp_args: {repeat_num: 2}
        tags: F19

    - ADown:
        args: {out_channels: 256}
    - CBFuse:
        source: [RT5, RT7, RT9, -1]
        args: {index: [2, 2, 2]}
    - RepNCSPELAN:
        args:
          out_channels: 512
          part_channels: 256
          process_channels: 128
          csp_args: {repeat_num: 2}
        tags: F22

    - ADown:
        args: {out_channels: 512}
    - CBFuse:
        source: [RT7, RT9, -1]
        args: {index: [3, 3]}
    - RepNCSPELAN:
        args:
          out_channels: 1024
          part_channels: 512
          process_channels: 256
          csp_args: {repeat_num: 2}
        tags: F25
    - ADown:
        args: {out_channels: 1024}
    - CBFuse:
        source: [RT9, -1]
        args: {index: [4]}
    - RepNCSPELAN:
        args:
          out_channels: 1024
          part_channels: 512
          process_channels: 256
          csp_args: {repeat_num: 2}
        tags: F28

  neck:
    - SPPELAN:
        args: {out_channels: 512}
        tags: N3

    - UpSample:
        args: {scale_factor: 2, mode: nearest}
    - Concat:
        source: [-1, F25]
    - RepNCSPELAN:
        args:
          out_channels: 512
          part_channels: 512
          process_channels: 256
          csp_args: {repeat_num: 2}
        tags: N4

    - UpSample:
        args: {scale_factor: 2, mode: nearest}
    - Concat:
        source: [-1, F22]

  head:
    - RepNCSPELAN:
        args:
          out_channels: 256
          part_channels: 256
          process_channels: 128
          csp_args: {repeat_num: 2}
        tags: P3

    - ADown:
        args: {out_channels: 256}
    - Concat:
        source: [-1, N4]
    - RepNCSPELAN:
        args:
          out_channels: 512
          part_channels: 512
          process_channels: 256
          csp_args: {repeat_num: 2}
        tags: P4

    - ADown:
        args: {out_channels: 512}
    - Concat:
        source: [-1, N3]
    - RepNCSPELAN:
        args:
          out_channels: 512
          part_channels: 1024
          process_channels: 512
          csp_args: {repeat_num: 2}
        tags: P5

  detection:
    - MultiheadDetection:
        source: [P3, P4, P5]
        tags: Main
        output: True

  auxiliary:
    - Conv:
        args: {out_channels: 64, kernel_size: 3, stride: 2}
        source: 0
    - Conv:
        args: {out_channels: 128, kernel_size: 3, stride: 2}
    - RepNCSPELAN:
        args:
          out_channels: 256
          part_channels: 128
          process_channels: 64
          csp_args: {repeat_num: 2}

    - ADown:
        args: {out_channels: 256}
    - CBFuse:
        source: [RT5, RT7, RT9, -1]
        args: {index: [2, 2, 2]}
    - RepNCSPELAN:
        args:
          out_channels: 256
          part_channels: 128
          process_channels: 64
          csp_args: {repeat_num: 2}
        tags: A3

    - ADown:
        args: {out_channels: 256}
    - CBFuse:
        source: [RT5, RT7, RT9, -1]
        args: {index: [2, 2, 2]}
    - RepNCSPELAN:
        args:
          out_channels: 512
          part_channels: 256
          process_channels: 128
          csp_args: {repeat_num: 2}
        tags: A4

    - ADown:
        args: {out_channels: 512}
    - CBFuse:
        source: [RT7, RT9, -1]
        args: {index: [3, 3]}
    - RepNCSPELAN:
        args:
          out_channels: 1024
          part_channels: 512
          process_channels: 256
          csp_args: {repeat_num: 2}
        tags: A5

    - MultiheadDetection:
        source: [A3, A4, A5]
        tags: AUX
        output: True
